version: '3.7'

services:
  eventStore:
    image: eventstore/eventstore
    ports:
      - 1113:1113
      - 2113:2113
    environment:
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
